// Graph editing is local until save; execution always references a saved backend graph.
const fs=require('fs'),path=require('path'),{execFile}=require('child_process');
function toolPath(){return [path.join(__dirname,'framework/tools/scenario_graph.py'),path.join(__dirname,'../tools/scenario_graph.py')].find(fs.existsSync);}
async function graphApi(root,action,{graphId,graph,scenario}={},execute=execFile){
 const script=toolPath();if(!script)throw new Error('接線執行工具尚未安裝');
 const args=[script,'--root',root,'--action',action];if(graphId)args.push('--graph-id',graphId);if(scenario)args.push('--scenario',scenario);
 return new Promise((resolve,reject)=>{const child=execute('python',args,{cwd:root,windowsHide:true,timeout:15000,maxBuffer:8*1024*1024,encoding:'utf8',env:{...process.env,PYTHONUTF8:'1'}},(error,stdout,stderr)=>{if(error)return reject(new Error(stderr || stdout || error.message));try{resolve(JSON.parse(stdout));}catch(e){reject(e);}});if(graph)child.stdin.end(JSON.stringify(graph));});
}
function examples(){
 const base=[path.join(__dirname,'../testcase'),path.join(__dirname,'resources/testcase')].find(p=>fs.existsSync(path.join(p,'cases.json')));if(!base)return {};
 const data=JSON.parse(fs.readFileSync(path.join(base,'cases.json'),'utf8'));const result={};
 for(const item of data.cases || [])if(!result[item.expected_scenario])result[item.expected_scenario]={text:fs.readFileSync(path.join(base,item.prompt_file),'utf8'),case_id:item.id};return result;
}
function placeholder(cases,scenario,provider,model){const item=cases[scenario] || cases.default;return (item?'例如：'+item.text:'請描述此場景要完成的工作。')+'\n目前編輯：'+scenario+' · '+provider+' / '+(model || 'CLI 預設')+'；選場景不會覆寫你輸入的需求。';}
const markup=`<section class="card graph-studio"><h2>場景接線工作室</h2><div class="muted">v1 每節點最多一條入邊，可分支但不能合流。審查節點不寫產物。拖移節點排列。按「接線」後依序點來源與目標；選取線條可編輯或刪除。儲存只更新設定，執行必須另按「執行已儲存接線」。</div>
<div class="row"><select id="graphList" aria-label="已儲存接線"></select><button id="graphNew" class="ghost">新增接線</button><button id="graphRefresh" class="ghost">重新載入</button><button id="graphSave" class="primary">儲存接線</button><button id="graphRun" class="ghost">執行已儲存接線</button><button id="graphDelete" class="ghost">刪除此接線</button></div>
<div class="row"><label>圖 ID <input id="graphId" type="text"></label><label>名稱 <input id="graphLabel" type="text"></label><label>場景 ID（英數、底線、連字號）<input id="graphScenario" type="text"></label><label><input id="graphOptIn" type="checkbox">明確允許此圖使用 OpenCode</label></div>
<div class="row"><button id="graphAdd" class="ghost">＋節點</button><button id="graphConnect" class="ghost">接線</button><label>選取節點／連線 <select id="graphItems" aria-label="選取節點或連線"></select></label><button id="graphRemove" class="ghost" disabled>刪除選取</button><button id="graphEntry" class="ghost">設為起點</button><span id="graphStatus" class="muted">載入接線…</span></div>
<div class="graph-layout"><div id="graphCanvas" tabindex="0" aria-label="接線畫布"><svg id="graphEdges" aria-label="路由連線"></svg><div id="graphNodes"></div></div><aside class="graph-inspector"><div id="graphSelection" class="muted">選擇節點或連線</div><label>標籤 <input id="graphItemLabel" type="text"></label><div id="graphNodeFields"><label>角色 <select id="graphKind"><option value="task">任務</option><option value="review">審查</option></select></label><label>供應商 <select id="graphProvider"><option value="codex">Codex</option><option value="claude">Claude</option><option value="opencode">OpenCode</option></select></label><label>模型 <input id="graphModel" type="text" placeholder="CLI 預設；OpenCode 必填 provider/model"></label><label>此節點任務 <textarea id="graphTask" rows="4"></textarea></label><label>必要產物（每行一個相對路徑）<textarea id="graphExpects" rows="2"></textarea></label></div><div id="graphEdgeFields"><label>啟動條件 <select id="graphCondition"><option value="success">前節點成功</option><option value="quota_exhausted">前節點額度耗盡</option></select></label></div></aside></div></section>`;
const styles=`.graph-layout{display:grid;grid-template-columns:minmax(280px,1fr) 250px;gap:12px;margin-top:12px}.graph-inspector{padding:10px;border:1px solid var(--line);border-radius:6px}.graph-inspector label{display:block;margin:8px 0}.graph-inspector input,.graph-inspector select,.graph-inspector textarea{width:100%;box-sizing:border-box}#graphCanvas{position:relative;height:410px;overflow:auto;border:1px solid var(--line);border-radius:7px;background-color:var(--vscode-editor-background,#111720);background-image:radial-gradient(#4d5b6b 1px,transparent 1px);background-size:20px 20px}#graphEdges,#graphNodes{position:absolute;left:0;top:0;width:1600px;height:1000px}#graphEdges{overflow:visible}#graphNodes{pointer-events:none}.graph-node{position:absolute;width:170px;min-height:70px;box-sizing:border-box;padding:10px;border:1px solid #788ba6;border-radius:8px;background:var(--card,#1d2533);cursor:grab;user-select:none;touch-action:none;pointer-events:auto}.graph-node.selected{border:2px solid var(--gold,#d4af37)}.graph-node small{display:block;margin-top:7px;color:var(--muted,#aaa);overflow-wrap:anywhere}.graph-node.entry:before{content:'起點';float:right;color:var(--gold,#d4af37);font-size:10px}.graph-inspector textarea{min-height:55px}@media(max-width:650px){.graph-layout{grid-template-columns:1fr}.graph-inspector{display:block}}`;
function mount(document,send){
 const $=id=>document.getElementById(id);if(!document.createElementNS || !$('graphCanvas')?.addEventListener)return {message(){},scenario(){}};
 let graph=null,selected=null,dirty=false,linking=false,source=null,savedId=null;
 const copy=value=>JSON.parse(JSON.stringify(value));const status=text=>$('graphStatus').textContent=text;
 function cancelLink(){linking=false;source=null;$('graphConnect').textContent='接線';$('graphConnect').setAttribute('aria-pressed','false');}
 function clearInspector(){selected=null;$('graphSelection').textContent='請從清單或畫布選擇節點／連線';for(const id of ['graphItemLabel','graphModel','graphTask','graphExpects'])$(id).value='';$('graphNodeFields').style.display='none';$('graphEdgeFields').style.display='none';$('graphRemove').disabled=true;$('graphRemove').textContent='刪除選取';$('graphEntry').disabled=true;}
 function itemList(){const list=$('graphItems');list.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='選擇要編輯或刪除的項目';list.appendChild(empty);for(const n of graph.nodes){const item=document.createElement('option');item.value='node:'+n.id;item.textContent='節點 · '+n.label+' ['+n.id+']';list.appendChild(item);}for(const e of graph.edges){const item=document.createElement('option');item.value='edge:'+e.id;item.textContent='連線 · '+(node(e.source)?.label || e.source)+' → '+(node(e.target)?.label || e.target)+' · '+(e.label || e.condition)+' ['+e.id+']';list.appendChild(item);}list.value=selected?selected.type+':'+selected.id:'';}
 function changed(){dirty=true;status('尚未儲存；不影響目前執行中的任務。');}
 function formToGraph(){graph.id=$('graphId').value.trim();graph.label=$('graphLabel').value;graph.scenario=$('graphScenario').value.trim();graph.opencode_opt_in=$('graphOptIn').checked;}
 function load(value){cancelLink();clearInspector();graph=copy(value);savedId=graph.id;dirty=false;selected=null;$('graphId').value=graph.id;$('graphLabel').value=graph.label || graph.id;$('graphScenario').value=graph.scenario;$('graphOptIn').checked=!!graph.opencode_opt_in;render();status('已載入儲存版本；執行會使用此版本。');}
 function newGraph(){load({version:1,id:'graph-'+Date.now().toString(36),label:'新的場景接線',scenario:$('scenario').value || 'default',entry_node:'n1',opencode_opt_in:false,nodes:[{id:'n1',label:'主要任務',kind:'task',provider:'codex',model:null,task_text:'完成使用者要求並驗證產物。',x:50,y:60,expects:[]}],edges:[]});savedId=null;changed();}
 function node(id){return graph.nodes.find(n=>n.id===id);}
 function select(type,id){cancelLink();selected={type,id};$('graphRemove').disabled=false;$('graphRemove').textContent=type==='node'?'刪除此節點與相連線':'刪除此連線';$('graphEntry').disabled=type!=='node';render();const value=type==='node'?node(id):graph.edges.find(e=>e.id===id);$('graphSelection').textContent=(type==='node'?'節點：':'連線：')+id;$('graphItemLabel').value=value.label || '';$('graphNodeFields').style.display=type==='node'?'block':'none';$('graphEdgeFields').style.display=type==='edge'?'block':'none';if(type==='node'){$('graphKind').value=value.kind || 'task';$('graphProvider').value=value.provider;$('graphModel').value=value.model || '';$('graphTask').value=value.task_text || '';$('graphExpects').value=(value.expects || []).join('\n');$('graphExpects').disabled=value.kind==='review';}else $('graphCondition').value=value.condition;}
 function edges(){const svg=$('graphEdges');svg.replaceChildren();for(const edge of graph.edges){const a=node(edge.source),b=node(edge.target);if(!a||!b)continue;const x1=a.x+170,y1=a.y+35,x2=b.x,y2=b.y+35;const group=document.createElementNS('http://www.w3.org/2000/svg','g');const line=document.createElementNS('http://www.w3.org/2000/svg','path');line.setAttribute('d',`M${x1} ${y1} C${x1+75} ${y1},${x2-75} ${y2},${x2} ${y2}`);line.setAttribute('fill','none');line.setAttribute('stroke',selected?.type==='edge'&&selected.id===edge.id?'#e4bd44':'#82a5d9');line.setAttribute('stroke-width','5');line.style.cursor='pointer';line.onclick=e=>{e.stopPropagation();select('edge',edge.id);};const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',(x1+x2)/2);text.setAttribute('y',(y1+y2)/2-8);text.setAttribute('fill','#b5c8e3');text.setAttribute('font-size','12');text.textContent=(edge.label || (edge.condition==='success'?'成功':'額度耗盡'))+' →';text.onclick=()=>select('edge',edge.id);const hit=document.createElementNS('http://www.w3.org/2000/svg','path');hit.setAttribute('d',`M${x1} ${y1} C${x1+75} ${y1},${x2-75} ${y2},${x2} ${y2}`);hit.setAttribute('fill','none');hit.setAttribute('stroke','transparent');hit.setAttribute('stroke-width','22');hit.setAttribute('pointer-events','stroke');hit.style.cursor='pointer';hit.onclick=line.onclick;group.appendChild(hit);group.appendChild(line);group.appendChild(text);svg.appendChild(group);}}
 function render(){if(!graph)return;itemList();edges();const area=$('graphNodes');area.replaceChildren();for(const n of graph.nodes){const box=document.createElement('div');box.className='graph-node'+(selected?.type==='node'&&selected.id===n.id?' selected':'')+(graph.entry_node===n.id?' entry':'');box.style.left=n.x+'px';box.style.top=n.y+'px';box.tabIndex=0;box.setAttribute('role','button');box.setAttribute('aria-label',n.label);const title=document.createElement('b');title.textContent=n.label;box.appendChild(title);const detail=document.createElement('small');detail.textContent=n.provider+' / '+(n.model || 'CLI 預設');box.appendChild(detail);let drag=null;
 box.onpointerdown=e=>{if(linking){if(!source){source=n.id;status('再點選目標節點。');}else if(source!==n.id){graph.edges.push({id:'e'+Date.now().toString(36),source,target:n.id,condition:'success',label:''});cancelLink();changed();render();}return;}selected={type:'node',id:n.id};drag={clientX:e.clientX,clientY:e.clientY,x:n.x,y:n.y,moved:false};box.setPointerCapture(e.pointerId);};
 box.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.clientX,dy=e.clientY-drag.clientY;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;n.x=Math.max(0,Math.min(1400,drag.x+dx));n.y=Math.max(0,Math.min(900,drag.y+dy));box.style.left=n.x+'px';box.style.top=n.y+'px';edges();};
 box.onpointerup=()=>{if(!drag)return;const moved=drag.moved;drag=null;select('node',n.id);if(moved)changed();};box.onkeydown=e=>{if(e.key==='Enter')select('node',n.id);};area.appendChild(box);}}
 function update(){if(!graph||!selected)return;const value=selected.type==='node'?node(selected.id):graph.edges.find(e=>e.id===selected.id);value.label=$('graphItemLabel').value;if(selected.type==='node'){value.kind=$('graphKind').value;value.provider=$('graphProvider').value;value.model=$('graphModel').value.trim() || null;value.task_text=$('graphTask').value;value.expects=value.kind==='review'?[]:$('graphExpects').value.split('\n').map(s=>s.trim()).filter(Boolean);$('graphExpects').disabled=value.kind==='review';if(value.kind==='review')$('graphExpects').value='';}else value.condition=$('graphCondition').value;changed();render();}
 for(const id of ['graphItemLabel','graphKind','graphProvider','graphModel','graphTask','graphExpects','graphCondition'])$(id).oninput=update;
 $('graphProvider').onchange=()=>{$('graphModel').value='';update();};
 for(const id of ['graphId','graphLabel','graphScenario','graphOptIn'])$(id).oninput=()=>{formToGraph();changed();};
 $('graphNew').onclick=newGraph;$('graphRefresh').onclick=()=>send({type:'graphList'});$('graphList').onchange=()=>send({type:'graphGet',graphId:$('graphList').value});
 $('graphSave').onclick=()=>{formToGraph();send({type:'graphSave',graph:copy(graph)});status('儲存並驗證接線…');};
 $('graphDelete').onclick=()=>{if(savedId)send({type:'graphDelete',graphId:savedId});};
 $('graphAdd').onclick=()=>{const id='n'+Date.now().toString(36);graph.nodes.push({id,label:'新任務',kind:'task',provider:'codex',model:null,task_text:'完成此步驟並提供可驗證結果。',x:260+graph.nodes.length*25,y:80+graph.nodes.length*45,expects:[]});changed();select('node',id);};
 $('graphConnect').onclick=()=>{if(linking){cancelLink();status('已取消接線；可從清單選取並刪除項目。');return;}linking=true;source=null;$('graphConnect').textContent='取消接線（Esc）';$('graphConnect').setAttribute('aria-pressed','true');status('請先點選來源節點，再點目標。Esc 或再按此按鈕取消。');};
 $('graphItems').onchange=()=>{cancelLink();const value=$('graphItems').value;if(!value){clearInspector();render();return;}const split=value.indexOf(':');select(value.slice(0,split),value.slice(split+1));};
 const escape=e=>{if(e.key==='Escape'){cancelLink();status('已取消接線；可選取節點或連線。');}};
 $('graphCanvas').onkeydown=escape;document.addEventListener?.('keydown',escape);
 $('graphRemove').onclick=()=>{cancelLink();if(!selected){status('請先從清單選擇要刪除的節點或連線。');return;}if(selected.type==='node'){graph.nodes=graph.nodes.filter(n=>n.id!==selected.id);graph.edges=graph.edges.filter(e=>e.source!==selected.id&&e.target!==selected.id);if(graph.entry_node===selected.id)graph.entry_node=graph.nodes[0]?.id || '';}else graph.edges=graph.edges.filter(e=>e.id!==selected.id);clearInspector();changed();render();};
 $('graphEntry').onclick=()=>{if(selected?.type==='node'){graph.entry_node=selected.id;changed();render();}};
 $('graphRun').onclick=()=>{if(dirty||!savedId){status('請先儲存接線，再執行。');return;}const requirement=$('req').value.trim();if(!requirement){status('請先在上方輸入本次需求；灰色範例不會自動執行。');return;}send({type:'graphRun',graphId:savedId,requirement});};
 return {scenario(value){if(!graph)return;$('graphScenario').placeholder=value;},message(m){if(m.type==='state'){const active=m.run;const running=active?.status==='running'&&active?.route?.mode==='graph';$('graphSave').disabled=running;$('graphDelete').disabled=running;}if(m.type==='graphList'){const items=m.result.graphs || m.result.items || [];const select=$('graphList');select.replaceChildren();for(const item of items){const option=document.createElement('option');option.value=item.id;option.textContent=item.label || item.id;select.appendChild(option);}if(savedId&&items.some(g=>g.id===savedId))select.value=savedId;else if(items.length)send({type:'graphGet',graphId:items[0].id});else newGraph();}else if(m.type==='graphLoaded'||m.type==='graphSaved'){load(m.result.graph || m.result);if(m.type==='graphSaved')send({type:'graphList'});}else if(m.type==='graphError'){cancelLink();status('未儲存／未執行：'+String(m.message).replace(/every node must be reachable[^\n]*/i,'有節點未連接起點；請連接或移除未連接節點。').replace(/entry must not have incoming edges/i,'起點不能有流入連線。請從清單選取指向起點的連線，按「刪除此連線」，再儲存。')+'（草稿已保留）');}}};
}
function clientScript(){return `const graphEditor=(${mount.toString()})(document,(message)=>vscode.postMessage(message));`;}
module.exports={graphApi,examples,placeholder,markup,styles,clientScript,mount};
