const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const editor=require('./wiring-editor'),routing=require('./routing');
function dom(){const elements=new Map();class E{constructor(){this.value='';this.checked=false;this.style={};this.children=[];}appendChild(x){this.children.push(x);}replaceChildren(...xs){this.children=xs;}setAttribute(k,v){this[k]=v;}addEventListener(){}setPointerCapture(){}}return {getElementById(id){if(!elements.has(id))elements.set(id,new E());return elements.get(id);},createElement(){return new E();},createElementNS(){return new E();}};}
const sample=()=>({version:1,id:'ui-test',label:'中文場景',scenario:'custom_task',entry_node:'a',opencode_opt_in:false,nodes:[{id:'a',label:'第一步',kind:'task',provider:'codex',model:null,task_text:'write one file',x:30,y:30,expects:[]}],edges:[]});
test('real canvas edits drag, connect, inspector, save and explicit run without overwriting requirement',()=>{
 const d=dom(),$=id=>d.getElementById(id),messages=[],ui=editor.mount(d,m=>messages.push(m));$('req').value='保留我的需求';ui.message({type:'graphLoaded',result:sample()});
 let box=$('graphNodes').children[0];box.onpointerdown({clientX:0,clientY:0,pointerId:1});box.onpointermove({clientX:40,clientY:50});box.onpointerup();
 $('graphAdd').onclick();$('graphConnect').onclick();$('graphNodes').children[0].onpointerdown({});$('graphNodes').children[1].onpointerdown({});
 $('graphSave').onclick();const graph=messages.at(-1).graph;assert.equal(graph.nodes[0].x,70);assert.equal(graph.nodes[0].y,80);assert.equal(graph.edges[0].source,'a');assert.equal(graph.nodes.length,2);
 ui.message({type:'graphSaved',result:graph});$('graphRun').onclick();assert.equal(messages.at(-1).type,'graphRun');assert.equal(messages.at(-1).requirement,'保留我的需求');
 box=$('graphNodes').children[0];box.onpointerdown({clientX:0,clientY:0,pointerId:2});box.onpointerup();$('graphKind').value='review';$('graphKind').oninput();assert.equal($('graphExpects').disabled,true);
 $('graphTask').value='新的審查任務';$('graphTask').oninput();$('graphRun').onclick();assert.match($('graphStatus').textContent,/先儲存/);$('graphSave').onclick();assert.equal(messages.at(-1).graph.nodes[0].task_text,'新的審查任務');assert.deepEqual(messages.at(-1).graph.nodes[0].expects,[]);
 ui.message({type:'state',run:{status:'running',route:{mode:'graph'}}});assert.equal($('graphSave').disabled,true);assert.equal($('req').value,'保留我的需求');
});
test('production graph CLI persists Chinese labels, previews digest and reloads edits',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-ui-'));let g=sample();await editor.graphApi(root,'save',{graph:g});g=await editor.graphApi(root,'preview',{graphId:g.id});assert.match(g.digest,/^[a-f0-9]{64}$/);assert.equal(g.label,'中文場景');g.nodes[0].task_text='修改內容';await editor.graphApi(root,'save',{graph:g});assert.equal((await editor.graphApi(root,'get',{graphId:g.id})).nodes[0].task_text,'修改內容');await editor.graphApi(root,'delete',{graphId:g.id});assert.deepEqual((await editor.graphApi(root,'list')).graphs,[]);});
test('placeholders derive actual testcase prompt and package contains same canonical bytes',()=>{const cases=editor.examples();assert.equal(Object.keys(cases).length,7);assert.match(editor.placeholder(cases,'3d_modeling','codex','sample'),/sample/);const target=fs.mkdtempSync(path.join(os.tmpdir(),'examples-'));require('./bundle-examples').bundle(undefined,target);assert.deepEqual(fs.readFileSync(path.join(target,'cases.json')),fs.readFileSync(path.join(__dirname,'../testcase/cases.json')));});
test('OpenCode-first requires explicit model and forwards it to real Python preset',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'preset-ui-'));await assert.rejects(routing.applyPreset(root,'opencode-first'),/provider\/model/);await routing.applyPreset(root,'opencode-first',undefined,{model:'vendor/example'});const catalog=await routing.getCatalog(root);assert.equal(catalog.scenarios[0].provider,'opencode');});
test('graph completion envelope is scoped and cannot masquerade as seven-phase proof',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-proof-'));fs.mkdirSync(path.join(root,'log'));const run={run_id:'current',started_at:100,route:{mode:'graph',graph_id:'ui-test',graph_digest:'a'.repeat(64),graph_snapshot:sample()}};const result={schema_version:1,run_id:'current',started_at:101,ended_at:102,status:'completed',graph_id:'ui-test',graph_digest:'a'.repeat(64),graph_states:{a:'ok'},activated_edges:[],task_delivery_verified:false};const file=path.join(root,'log/graph-result-current.json');function check(value){fs.writeFileSync(file,JSON.stringify(value));return routing.taskResult(root,run,0);}assert.equal(check(result).status,'completed');assert.match(check(result).reason,/未驗證七階段/);for(const edit of [{run_id:'other'},{graph_digest:'b'.repeat(64)},{ended_at:99},{schema_version:0},{task_delivery_verified:true},{graph_states:{other:'ok'}},{graph_states:{a:'bogus'}},{status:'unknown'},{activated_edges:['missing']}])assert.equal(check({...result,...edit}).status,'incomplete');});
test('formal webview host bridge persists actual canvas save and reload through Python',async()=>{const dashboard=require('./dashboard');const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-bridge-'));const d=dom();let receive;const sent=[];const pending=[];let client;const host={html:'',onDidReceiveMessage(fn){receive=fn;return {dispose(){}};},postMessage(m){sent.push(m);client?.message(m);for(const waiter of pending.splice(0))waiter();}};const dispose=dashboard.wireDashboard(host,{root,onGraphApi:(action,options)=>editor.graphApi(root,action,options)});client=editor.mount(d,m=>receive(m));function waitFor(type){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('timeout '+type)),5000);const check=()=>{if(sent.some(m=>m.type===type)){clearTimeout(timer);resolve();}else pending.push(check);};check();});}try{client.message({type:'graphLoaded',result:sample()});d.getElementById('graphLabel').value='正式橋接中文';d.getElementById('graphLabel').oninput();d.getElementById('graphSave').onclick();await waitFor('graphSaved');assert.equal((await editor.graphApi(root,'get',{graphId:'ui-test'})).label,'正式橋接中文');await waitFor('graphList');assert.equal(d.getElementById('graphLabel').value,'正式橋接中文');}finally{dispose();}});
test('real webview sequential presets never leak OpenCode model into Claude preset',async()=>{
 const vm=require('vm'),dashboard=require('./dashboard');const root=fs.mkdtempSync(path.join(os.tmpdir(),'preset-sequence-'));const document=dom();let browserListener,hostListener,completed;const selections=[];
 // Use the full HTML script while the graph panel remains idle.
 const webview={html:'',postMessage:data=>browserListener?.({data}),onDidReceiveMessage:fn=>{hostListener=fn;return {dispose(){}};}};
 const dispose=dashboard.wireDashboard(webview,{root,onCatalog:()=>routing.getCatalog(root),onPreset:async(preset,reply,options)=>{try{selections.push({preset,...options});await routing.applyPreset(root,preset,undefined,options);completed.resolve();}catch(e){completed.reject(e);throw e;}}});
 try{vm.runInNewContext(webview.html.match(/<script>([\s\S]*?)<\/script>/)[1],{document,acquireVsCodeApi:()=>({postMessage:m=>hostListener(m)}),window:{addEventListener:(name,fn)=>browserListener=fn}});const $=id=>document.getElementById(id);
 async function apply(){const done=new Promise((resolve,reject)=>completed={resolve,reject});$('btnPreset').onclick();await done;}
 $('preset').value='opencode-first';$('preset').onchange();$('presetModel').value='deepseek/deepseek-test-model';await apply();assert.equal((await routing.getCatalog(root)).scenarios[0].model,'deepseek/deepseek-test-model');
 $('preset').value='review-codex-build-claude';$('preset').onchange();assert.equal($('presetModel').value,'');assert.equal($('presetModel').disabled,true);await apply();assert.equal(selections[1].model,undefined);const catalog=await routing.getCatalog(root);assert.ok(catalog.scenarios.every(s=>s.model!=='deepseek/deepseek-test-model'));const graph=await editor.graphApi(root,'get',{graphId:'review-codex-build-claude'});assert.ok(graph.nodes.every(n=>n.model===null));
 }finally{dispose();}
});
test('OpenCode model IDs with multiple nonempty segments pass the real route API',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'multi-model-'));await routing.applyPreset(root,'opencode-first',undefined,{model:'vendor/org/model'});await routing.saveRoute(root,{scenario:'review',provider:'opencode',model:'vendor/org/model'});assert.equal((await routing.getCatalog(root)).scenarios.find(s=>s.name==='review').model,'vendor/org/model');});
test('invalid incoming edge can be selected from list after rejected save, deleted and saved; deleting node removes edges',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-repair-')),d=dom(),$=id=>d.getElementById(id);let operation=Promise.resolve(),ui;const messages=[];
 ui=editor.mount(d,m=>{messages.push(m);if(m.type==='graphSave')operation=editor.graphApi(root,'save',{graph:m.graph}).then(result=>ui.message({type:'graphSaved',result}),e=>ui.message({type:'graphError',message:e.message}));});
 const g=sample();g.nodes.push({...g.nodes[0],id:'b',label:'第二節點',x:280});g.edges=[{id:'forward',source:'a',target:'b',condition:'success',label:'正向'}];ui.message({type:'graphLoaded',result:g});
 function reverse(){ $('graphConnect').onclick();$('graphNodes').children[1].onpointerdown({});$('graphNodes').children[0].onpointerdown({});}
 function choose(value){$('graphItems').value=value;$('graphItems').onchange();}
 reverse();$('graphSave').onclick();await operation;assert.match($('graphStatus').textContent,/起點不能有流入連線/);assert.match($('graphStatus').textContent,/草稿已保留/);assert.equal($('graphConnect').textContent,'接線');
 let draft=messages.filter(m=>m.type==='graphSave').at(-1).graph;const wrong=draft.edges.find(e=>e.target==='a');assert.ok($('graphItems').children.some(item=>item.value==='edge:'+wrong.id));
 $('graphConnect').onclick();choose('edge:'+wrong.id);assert.equal($('graphConnect').textContent,'接線');assert.equal($('graphRemove').textContent,'刪除此連線');$('graphRemove').onclick();assert.equal($('graphItemLabel').value,'');$('graphSave').onclick();await operation;assert.equal((await editor.graphApi(root,'get',{graphId:g.id})).edges.length,1);
 reverse();$('graphSave').onclick();await operation;choose('node:b');$('graphRemove').onclick();assert.equal($('graphNodeFields').style.display,'none');assert.equal($('graphRemove').disabled,true);$('graphSave').onclick();await operation;const saved=await editor.graphApi(root,'get',{graphId:g.id});assert.deepEqual(saved.nodes.map(n=>n.id),['a']);assert.deepEqual(saved.edges,[]);
});
test('connect mode cancels on toggle, Escape, selection, load and error without adding stray edges',()=>{const d=dom(),$=id=>d.getElementById(id),messages=[],ui=editor.mount(d,m=>messages.push(m));ui.message({type:'graphLoaded',result:sample()});$('graphConnect').onclick();$('graphConnect').onclick();assert.equal($('graphConnect').textContent,'接線');$('graphConnect').onclick();$('graphCanvas').onkeydown({key:'Escape'});assert.equal($('graphConnect').textContent,'接線');$('graphConnect').onclick();$('graphNodes').children[0].onpointerdown({});ui.message({type:'graphLoaded',result:sample()});assert.equal($('graphConnect').textContent,'接線');$('graphConnect').onclick();ui.message({type:'graphError',message:'every node must be reachable'});assert.equal($('graphConnect').textContent,'接線');$('graphSave').onclick();assert.deepEqual(messages.at(-1).graph.edges,[]);});
